-- Generated from src/catalog.json. Run after 001_ingredient_availability.sql.
-- New ingredients start in stock. Existing availability is preserved.
insert into public.ingredient_availability (ingredient_id, is_available) values
  ('sparkling-wine', true),
  ('orange-juice', true),
  ('vodka', true),
  ('lemon-juice', true),
  ('triple-sec', true),
  ('simple-syrup', true),
  ('whiskey', true),
  ('coffee-liqueur', true),
  ('irish-cream', true),
  ('heavy-cream', true),
  ('vanilla-ice-cream', true),
  ('ice', true),
  ('white-rum', true),
  ('pineapple-juice', true),
  ('coconut-cream', true),
  ('lime-juice', true),
  ('frozen-strawberries', true),
  ('tequila', true),
  ('margarita-mix', true),
  ('mint-extract', true),
  ('peach-schnapps', true),
  ('cranberry-juice', true),
  ('grenadine', true),
  ('dark-rum', true),
  ('blue-curacao', true),
  ('lemonade', true),
  ('gin', true),
  ('cola', true),
  ('ginger-beer', true),
  ('orange-curacao', true),
  ('orgeat', true),
  ('jack-daniels', true),
  ('peach-syrup', true),
  ('seltzer', true),
  ('watermelon-syrup', true),
  ('peach-cranberry-juice', true),
  ('strawberry-limeade', true),
  ('red-bull', true),
  ('tropical-red-bull', true),
  ('fireball', true)
on conflict (ingredient_id) do nothing;
